sudo: false
language: java

jdk:
  - openjdk8

script:
  - "mvn clean package"
  - "mvn cobertura:cobertura"
skip_cleanup: true
branch: open

after_success:
  - bash <(curl -s https://codecov.io/bash)


